add dev version

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -15,9 +15,11 @@ install_tctl() {
     local bin_path="${bin_install_path}/tctl"
 
     if [ "$version" == "dev" ]; then
+        [ -n "$ASDF_TCTL_DEV_PATH" ] ||  (>&2 echo 'Missing ASDF_TCTL_DEV_PATH' && exit 1)
         if [ -L "$bin_path" ]; then
             unlink "$bin_path"
         fi
+        echo ln -s "${ASDF_TCTL_DEV_PATH}" "$bin_path"
         ln -s "${ASDF_TCTL_DEV_PATH}" "$bin_path"
     else
         local download_url="$(get_download_url $version)"
