add dev version

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -8,22 +8,27 @@ ASDF_INSTALL_TYPE=${ASDF_INSTALL_TYPE:-version  }
 [ -n "$ASDF_INSTALL_PATH" ] || (>&2 echo 'Missing ASDF_INSTALL_PATH' && exit 1)
 
 install_tctl() {
-  local install_type=$1
-  local version=$2
-  local install_path=$3
-  local bin_install_path="$install_path/bin"
-  local download_url="$(get_download_url $version)"
+    local install_type=$1
+    local version=$2
+    local install_path=$3
+    local bin_install_path="$install_path/bin"
+    local bin_path="${bin_install_path}/tctl"
 
-  mkdir -p "${bin_install_path}"
+    if [ "$version" == "dev" ]; then
+        test -l "$bin_path" || ln -s "${ASDF_TCTL_DEV_PATH}" "$bin_path"
+    else
+        local download_url="$(get_download_url $version)"
 
-  local bin_path="${bin_install_path}/tctl"
-  echo "Downloading tctl from ${download_url}"
-  if curl -L -sf "$download_url" -o "$bin_path"; then
-    chmod +x $bin_path
-  else
-    echo "Failed to download tctl from ${download_url}. Does the version exist and is available in the requested $(get_cpu) architecture?"
-    exit 1
-  fi
+        mkdir -p "${bin_install_path}"
+
+        echo "Downloading tctl from ${download_url}"
+        if curl -L -sf "$download_url" -o "$bin_path"; then
+            chmod +x $bin_path
+        else
+            echo "Failed to download tctl from ${download_url}. Does the version exist and is available in the requested $(get_cpu) architecture?"
+            exit 1
+        fi
+    fi
 }
 
 get_arch() {
